services:
  readystackgo-publicweb:
    build: .
    image: ghcr.io/ams/readystackgo-publicweb:latest
    container_name: readystackgo-publicweb
    ports:
      - "8888:80"
    restart: unless-stopped
